kind: template
load: pipeline-builder.star
data:
  pipelines:
  - kind: pipeline
    name: editorconfig-checker
    steps:
      - name: check-editorconfig
        image: mstruebing/editorconfig-checker
        commands:
          - ec -v --exclude .git .
    trigger:
      event:
        - pull_request

  - kind: pipeline
    name: markdown-checker
    steps:
      - name: check-links
        # Source: https://github.com/tcort/markdown-link-check
        image: ghcr.io/tcort/markdown-link-check:stable
        commands:
          - find . -name *.md -not -path "./node_modules/*" | xargs -n1 markdown-link-check --config .markdown-lint-check.config.json
    trigger:
      event:
        - pull_request

  - kind: pipeline
    name: nuxt3-test-and-lint

    steps:
      - name: install
        image: node:16.14.2
        commands:
          - cd app
          - npm ci

      - name: build
        image: node:16.14.2
        depends_on: [install]
        commands:
          - cd app
          - npm run build

      - name: lint
        image: node:16.14.2
        depends_on: [install]
        commands:
          - cd app
          - npm run lint

      - name: test
        image: node:16.14.2
        depends_on: [install]
        commands:
          - cd app
          - npm run test

    trigger:
      event:
        - pull_request
