version: '3'

services:
  database:
    restart: unless-stopped
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_PORT: "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
  pgweb:
    restart: unless-stopped
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres?sslmode=disable
    depends_on:
      database:
        condition: service_healthy
