context: default

metadata:
  org: "github.com/sidestream-tech/"
  maintainer: "DevOps"
  description: "Desired State File of the default fullstack-nuxt3 deployment"

settings:
  kubeContext: "arn:aws:eks:eu-central-1:802385070966:cluster/eks-cluster-sidestream"
  globalMaxHistory: 5

namespaces:
  fullstack-nuxt3-dummy:
    protected: false

helmRepos:
  sidechart: "https://$SIDECHART_USERNAME:$SIDECHART_TOKEN@raw.githubusercontent.com/sidestream-tech/helm-charts/gh-pages/"
  bitnami: "https://charts.bitnami.com/bitnami"

apps:
  fullstack-nuxt3-dummy:
    namespace: "fullstack-nuxt3-dummy"
    enabled: true
    chart: "sidechart/sidechart"
    version: "0.2.1"
    valuesFile: values-fullstack-nuxt3.yml
    test: false
    protected: false
    priority: -1
    wait: true
    helmFlags: [
      "--atomic",
    ]
    set:
      "commitShortSHA": "$DRONE_COMMIT_SHA"
      "image.tag": "$DRONE_COMMIT_SHA"
      "imageCredentials.password": "$GITHUB_PACKAGES_TOKEN"

  postgresql:
    namespace: "fullstack-nuxt3-dummy"
    enabled: true
    chart: "bitnami/postgresql"
    version: "11.6.6"
    valuesFile: "values-postgresql.yml"
    test: false
    protected: false
    priority: -2
    wait: true
