# This workflow initializes a newly created repository.
#
# Initialization encompasses:
# - TBD

name: Initialize the repository
on:
  create:
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      GH_REF: ${{ github.ref }}
    steps:
      - name: Echo
        run: |
          echo "New repository created"
          echo $GH_REF
